apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony-demo
  labels:
    app.kubernetes.io/instance: symfony
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: demo
    app.kubernetes.io/version: 1.0
    helm.sh/chart: demo-0.1
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: symfony
      app.kubernetes.io/name: demo
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/instance: symfony
        app.kubernetes.io/name: demo
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
