apiVersion: v1
kind: Service
metadata:
  name: symfony-demo
  labels:
    app.kubernetes.io/instance: symfony
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: demo
    app.kubernetes.io/version: 1.0
    helm.sh/chart: demo-0.1
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: symfony
    app.kubernetes.io/name: demo
